{
 "title": "PV Own Consumption",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Own Consumption from PV (not from grid)",
   "type": "gauge",
   "description": "The total home consumption during the time period selected, minus the energy consumed from the grid during the same time range.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"Total home consumption\") - max(\"Total home consumption Grid\") + min(\"Total home consumption Grid\")  - min(\"Total home consumption\")  FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Own Consumption (PV Yield - Grid Ingestion)",
   "type": "gauge",
   "description": "Total PV energy during time range, minus grid ingestion. This includes charge/discharge losses.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "SELECT max(\"Total DC PV energy (sum of all PV inputs) (f32)\") - min(\"Total DC PV energy (sum of all PV inputs) (f32)\") - max(\"Total energy AC-side to grid (f32)\") + min(\"Total energy AC-side to grid (f32)\") FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "Total DC PV energy (sum of all PV inputs) (f32)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home Consumption and Grid Ingestion",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Home Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"Total home consumption\") - min(\"Total home consumption\")FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"Total home consumption Grid\") - min(\"Total home consumption Grid\") FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PV Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"Total DC PV energy (sum of all PV inputs) (f32)\") - min(\"Total DC PV energy (sum of all PV inputs) (f32)\") FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid Ingestion",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"Total energy AC-side to grid (f32)\") - min(\"Total energy AC-side to grid (f32)\") FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}