{
 "title": "PV Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Home Usage",
   "type": "gauge",
   "description": "This includes power delivered to wallbox",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Home own consumption" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "pv",
     "select": [
      [
       { "params": [ "PV production" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Charge Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "pv",
     "query": "SELECT last(\"Battery Charge\") *-1 FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Battery Charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Battery SOC",
     "measurement": "pv",
     "query": "SELECT \"Act. state of charge\" FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Act. state of charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "To Grid",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "pv",
     "query": "SELECT last(\"Home own consumption from grid\") *-1 FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Ingestion",
   "type": "stat",
   "description": "Energy ingested during the time range selected",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "select max(\"Total energy AC-side to grid (f32)\") - min(\"Total energy AC-side to grid (f32)\") from pv where $timeFilter",
     "select": [
      [
       { "params": [ "Home own consumption from grid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "∑Grid Consumption",
   "type": "stat",
   "description": "How much energy was consumed from the grid during the time range selected?",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "pv",
     "query": "SELECT max(\"Total home consumption Grid\") - min(\"Total home consumption Grid\") FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Total home consumption Grid" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Savings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "SELECT (0.09*last(\"Total energy AC-side to grid (f32)\") + 0.3*(last(\"Total yield\")-last(\"Total energy AC-side to grid (f32)\")))/1000 FROM \"pv\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Total yield" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Yield",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "pv",
     "query": "SELECT max(\"Total yield\")-min(\"Total yield\") FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Total yield" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "∑Consumption",
   "type": "stat",
   "description": "How much energy did the home consume during the time range selected?",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "pv",
     "query": "SELECT max(\"Total home consumption\") - min(\"Total home consumption\") FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Total home consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "watt", "label": "Power (W)" }
   ],
   "targets": [
    {
     "alias": "Home Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Home own consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "PV production" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid Consumption (-) / Ingestion (+)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Battery Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Battery Charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Wallbox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ebox",
     "query": "SELECT 230*(mean(\"CurrentPhase1\")+mean(\"CurrentPhase2\")+mean(\"CurrentPhase3\")) FROM \"ebox\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "CurrentPhase1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "alias": "Battery SOC %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Battery actual SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Discharging Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "SELECT mean(\"Battery Charge\") *-1 FROM \"pv\" WHERE $timeFilter and \"Battery Charge\" >= 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Battery Charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Charging Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Battery Charge\") *-1 FROM \"pv\" WHERE $timeFilter and \"Battery Charge\" < 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power by String",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "String 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Power DC1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "String 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Power DC2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Temperature / Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Battery Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Battery temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Battery Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Battery voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}