{
 "title": "PV Self Consumption vs. Self Sufficiency",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Self Sufficiency Ever",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "SELECT (last(\"Total home consumption PV\")+last(\"Total home consumption Battery\")) / last(\"Total home consumption\") FROM \"pv\"",
     "select": [
      [
       { "params": [ "Total yield" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Self Sufficiency/Time Range",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "select (last(\"Total home consumption PV\")-first(\"Total home consumption PV\")+last(\"Total home consumption Battery\")-first(\"Total home consumption Battery\")) / (last(\"Total home consumption\") - first(\"Total home consumption\")) FROM \"pv\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Total yield" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Self Consumption Ever",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "SELECT last(\"Total home consumption rate\") FROM \"pv\"",
     "select": [
      [
       { "params": [ "Total home consumption PV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Self Consumption/TIme Range",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "select 1-mean(grid_ingestion_in_time_range) / mean(total_yield_in_time_range) from (select -sum(Wh) as grid_ingestion_in_time_range from (select time, e, t, e*t/1000000000/3600 as Wh from (select mean(el) as e, mean(tapp) as t from (select el, tapp from (select Elapsed(\"Total active power (powermeter)\") as el from pv where $timeFilter), (select \"Total active power (powermeter)\" as tapp from pv where $timeFilter)) group by time(1s)) where t<0)), (select (last(\"Total yield\")-first(\"Total yield\")) as total_yield_in_time_range from pv where $timeFilter)",
     "select": [
      [
       { "params": [ "Total home consumption PV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Savings Ever",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "SELECT (0.09*last(\"Total energy AC-side to grid (f32)\") + 0.3*(last(\"Total yield\")-last(\"Total energy AC-side to grid (f32)\")))/1000 FROM \"pv\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Total yield" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "watt", "label": "Power (W)" }
   ],
   "targets": [
    {
     "alias": "Home Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Home own consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "PV production" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid Consumption (-) / Ingestion (+)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Battery Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Battery Charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "alias": "Battery SOC %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Battery actual SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Charging Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "query": "SELECT mean(\"Battery Charge\") *-1 FROM \"pv\" WHERE $timeFilter and \"Battery Charge\" <= 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Battery Charge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Discharging Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Battery Charge\") *-1 FROM \"pv\" WHERE $timeFilter and \"Battery Charge\" > 0 GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power by String",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "String 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Power DC1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "String 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv",
     "select": [
      [
       { "params": [ "Power DC2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}